# Generated by Django 4.2.8 on 2024-01-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0002_fun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=40)),
                ('Email', models.CharField(default='', max_length=40)),
                ('Message', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
