name: 'Workflow of Parent REPO'
on:
  push:
    branches: [main]

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Workflow Name
        shell: bash
        run: |
          echo "I am workflow of parent REPO"
      - name: Trigger Child workdlow REPO"
        uses: convictional/trigger-workflow-and-wait!v1.6.1
        with:
          owner: chakratechgeek
          repo: ec2configAnsible
          github_token: ${{ secrets.ACCESS_KEY }}
          workflow_file_name: ansible_ec2.yml
          ref: main 
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true   

