name: Trigger Workflow 2 on Push

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow 2
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}  # Replace with your own secret name
          repository: chakratechgeek/ec2configAnsible  # Replace with your repository
          event-type: workflow_2_trigger
